image: alpine/edge
packages:
  - nodejs
  - npm
secrets:
  - 291f0e35-9b8d-43ff-844c-77c5f29c1876
environment:
  NETLIFY_SITE_ID: 390b392a-a898-491b-8500-79aa30f724d6
tasks:
  - install-deps: |
      cd mcfly
      npm i
  - build: |
      cd mcfly/site
      npm run build
  - deploy: |
      cd mcfly/site
      {
        set +x
        . ~/.buildsecrets
        set -x
      }
      export NETLIFY_AUTH_TOKEN
      npm site run deploy