packages:
  - 'packages/**'
  - 'templates/**'
  - 'site'
  - 'demo'
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  netlify-cli: false
  sharp: false
  unix-dgram: false
  web-component-base: true
minimumReleaseAgeExclude:
  - '@mcflyjs/config@0.3.0-alpha'
  - '@mcflyjs/core@0.9.0-alpha'
  - '@mcflyjs/fastify@0.1.0'
