packages:
  - "packages/**"
  - "templates/**"
  - "site/**"
allowBuilds:
  '@parcel/watcher': false
  esbuild: true
  netlify-cli: false
  sharp: false
  unix-dgram: false
  web-component-base: true
